import { SupabaseClient } from '@supabase/supabase-js';

export default async function createGroup(
  client: SupabaseClient,
  userId: string,
  name: string,
  description?: string,
  coverImageUrl?: string
) {
  const { data: groupData, error: groupError } = await client
    .from('groups')
    .insert({
      name,
      description,
      created_by: userId,
      invite_code: '', // Will be generated by the trigger
      cover_image_url: coverImageUrl,
    })
    .select()
    .single();

  if (groupError) {
    console.error(groupError);
    throw groupError;
  }

  const { error: memberError } = await client.from('group_members').insert({
    group_id: groupData.id,
    user_id: userId,
    relationship_label: 'Creator',
    role: 'admin',
  });

  if (memberError) {
    throw memberError;
  }

  return { data: groupData, error: null };
}
