import { useCallback, useEffect, useState } from 'react';
import {
  GroupInvitation,
  supabase,
  type Group,
  type GroupMember,
  type Profile,
} from '@/utils/supabase';
import { useAuth } from '@/utils/useAuth';

export type UserGroup = Group & {
  group_members: (GroupMember & {
    profiles: Profile;
  })[];
};

type UseGroupsReturn = {
  groups: UserGroup[];
  isLoading: boolean;
  error: string | null;
  refetch: () => Promise<void>;
  createGroup: (name: string, description?: string) => Promise<Group | null>;
  inviteToGroup: (groupId: string, name: string) => Promise<GroupInvitation | null>;
  removeMemberFromGroup: (memberId: string, groupId: string) => Promise<boolean>;
};

export function useGroups(): UseGroupsReturn {
  const { session } = useAuth();
  const [groups, setGroups] = useState<UserGroup[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchGroups = useCallback(async () => {
    if (!session?.user?.id) {
      setGroups([]);
      setIsLoading(false);
      return;
    }

    try {
      setIsLoading(true);
      setError(null);

      // First get groups where current user is a member
      const { data: userGroups, error: userGroupsError } = await supabase
        .from('group_members')
        .select('group_id')
        .eq('user_id', session.user.id)
        .eq('is_active', true);

      if (userGroupsError) {
        throw userGroupsError;
      }

      if (!userGroups || userGroups.length === 0) {
        setGroups([]);
        return;
      }

      const groupIds = userGroups.map((ug) => ug.group_id);

      // Then get all groups and their members for those groups
      const { data, error: fetchError } = await supabase
        .from('groups')
        .select(
          `
          *,
          group_members(
            id,
            group_id,
            user_id,
            relationship_label,
            role,
            joined_at,
            is_active,
            profiles(
              id,
              email,
              full_name,
              avatar_url
            )
          )
        `
        )
        .in('id', groupIds)
        .eq('group_members.is_active', true);

      if (fetchError) {
        throw fetchError;
      }

      setGroups(data || []);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to fetch groups';
      setError(errorMessage);
      console.error('Error fetching groups:', err);
    } finally {
      setIsLoading(false);
    }
  }, [session?.user?.id]);

  const createGroup = useCallback(
    async (name: string, description?: string): Promise<Group | null> => {
      if (!session?.user?.id) {
        throw new Error('User must be authenticated to create a group');
      }

      try {
        const { data: groupData, error: groupError } = await supabase
          .from('groups')
          .insert({
            name,
            description,
            created_by: session.user.id,
            invite_code: '', // Will be generated by the trigger
          })
          .select()
          .single();

        if (groupError) {
          throw groupError;
        }

        // Add the creator as an admin member
        const { error: memberError } = await supabase.from('group_members').insert({
          group_id: groupData.id,
          user_id: session.user.id,
          relationship_label: 'Creator',
          role: 'admin',
        });

        if (memberError) {
          throw memberError;
        }

        // Refresh the groups list
        await fetchGroups();

        return groupData;
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Failed to create group';
        setError(errorMessage);
        console.error('Error creating group:', err);
        return null;
      }
    },
    [session?.user?.id, fetchGroups]
  );

  const inviteToGroup = useCallback(
    async (groupId: string, name: string): Promise<GroupInvitation | null> => {
      try {
        const { data, error } = await supabase.rpc('group_invitations', {
          group_id: groupId,
          creator_id: session?.user?.id,
          name,
        });

        if (error) {
          throw error;
        }

        return data;
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Failed to invite to group';
        setError(errorMessage);
        console.error('Error inviting to group:', err);
        return null;
      }
    },
    [session?.user?.id]
  );

  const removeMemberFromGroup = useCallback(
    async (memberId: string, groupId: string): Promise<boolean> => {
      try {
        const { error } = await supabase
          .from('group_members')
          .delete()
          .eq('id', memberId)
          .eq('group_id', groupId);

        if (error) {
          throw error;
        }

        // Refresh the groups list
        await fetchGroups();
        return true;
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : 'Failed to remove member from group';
        setError(errorMessage);
        console.error('Error removing member from group:', err);
        return false;
      }
    },
    [fetchGroups]
  );

  useEffect(() => {
    fetchGroups();
  }, [fetchGroups]);

  return {
    groups,
    isLoading,
    error,
    refetch: fetchGroups,
    createGroup,
    inviteToGroup,
    removeMemberFromGroup,
  };
}
